// <auto-generated />
using System;
using Borgonha.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Borgonha.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BorgonhaDbContext))]
    partial class BorgonhaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Borgonha.Domain.Entities.Ingrediente", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("criado_em");

                    b.Property<decimal>("CustoUnitario")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("custo_unitario");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<decimal>("QuantidadeAtual")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("quantidade_atual");

                    b.Property<decimal>("QuantidadeMinima")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("quantidade_minima");

                    b.Property<string>("Unidade")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("unidade");

                    b.HasKey("Id")
                        .HasName("pk_ingredientes");

                    b.ToTable("ingredientes", (string)null);
                });

            modelBuilder.Entity("Borgonha.Domain.Entities.ItemVenda", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("PrecoUnitario")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("preco_unitario");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uuid")
                        .HasColumnName("produto_id");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade");

                    b.Property<Guid>("VendaId")
                        .HasColumnType("uuid")
                        .HasColumnName("venda_id");

                    b.HasKey("Id")
                        .HasName("pk_itens_venda");

                    b.HasIndex("ProdutoId")
                        .HasDatabaseName("ix_itens_venda_produto_id");

                    b.HasIndex("VendaId")
                        .HasDatabaseName("ix_itens_venda_venda_id");

                    b.ToTable("itens_venda", (string)null);
                });

            modelBuilder.Entity("Borgonha.Domain.Entities.MovimentacaoEstoque", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("timestamptz")
                        .HasColumnName("data_hora");

                    b.Property<Guid>("IngredienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("ingrediente_id");

                    b.Property<string>("Observacao")
                        .HasColumnType("text")
                        .HasColumnName("observacao");

                    b.Property<decimal>("Quantidade")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("quantidade");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("tipo");

                    b.Property<Guid?>("VendaId")
                        .HasColumnType("uuid")
                        .HasColumnName("venda_id");

                    b.HasKey("Id")
                        .HasName("pk_movimentacoes_estoque");

                    b.HasIndex("IngredienteId")
                        .HasDatabaseName("ix_movimentacoes_estoque_ingrediente_id");

                    b.HasIndex("VendaId")
                        .HasDatabaseName("ix_movimentacoes_estoque_venda_id");

                    b.ToTable("movimentacoes_estoque", null, t =>
                        {
                            t.HasCheckConstraint("ck_movimentacoes_estoque_tipo", "tipo IN ('entrada', 'saida')");
                        });
                });

            modelBuilder.Entity("Borgonha.Domain.Entities.Produto", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("criado_em");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<decimal>("PrecoVenda")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("preco_venda");

                    b.HasKey("Id")
                        .HasName("pk_produtos");

                    b.ToTable("produtos", (string)null);
                });

            modelBuilder.Entity("Borgonha.Domain.Entities.ReceitaItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("IngredienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("ingrediente_id");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uuid")
                        .HasColumnName("produto_id");

                    b.Property<decimal>("Quantidade")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("quantidade");

                    b.HasKey("Id")
                        .HasName("pk_receita_itens");

                    b.HasIndex("IngredienteId")
                        .HasDatabaseName("ix_receita_itens_ingrediente_id");

                    b.HasIndex("ProdutoId", "IngredienteId")
                        .IsUnique()
                        .HasDatabaseName("ix_receita_itens_produto_id_ingrediente_id");

                    b.ToTable("receita_itens", (string)null);
                });

            modelBuilder.Entity("Borgonha.Domain.Entities.Venda", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CriadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("criado_por");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("timestamptz")
                        .HasColumnName("data_hora");

                    b.Property<decimal>("Total")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("total");

                    b.Property<decimal>("Troco")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("troco");

                    b.Property<decimal>("ValorPago")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("valor_pago");

                    b.HasKey("Id")
                        .HasName("pk_vendas");

                    b.ToTable("vendas", (string)null);
                });

            modelBuilder.Entity("Borgonha.Domain.Entities.ItemVenda", b =>
                {
                    b.HasOne("Borgonha.Domain.Entities.Produto", null)
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_itens_venda_produtos_produto_id");

                    b.HasOne("Borgonha.Domain.Entities.Venda", null)
                        .WithMany("Itens")
                        .HasForeignKey("VendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_itens_venda_vendas_venda_id");
                });

            modelBuilder.Entity("Borgonha.Domain.Entities.MovimentacaoEstoque", b =>
                {
                    b.HasOne("Borgonha.Domain.Entities.Ingrediente", null)
                        .WithMany("Movimentacoes")
                        .HasForeignKey("IngredienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_movimentacoes_estoque_ingredientes_ingrediente_id");

                    b.HasOne("Borgonha.Domain.Entities.Venda", null)
                        .WithMany()
                        .HasForeignKey("VendaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_movimentacoes_estoque_vendas_venda_id");
                });

            modelBuilder.Entity("Borgonha.Domain.Entities.ReceitaItem", b =>
                {
                    b.HasOne("Borgonha.Domain.Entities.Ingrediente", null)
                        .WithMany()
                        .HasForeignKey("IngredienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_receita_itens_ingredientes_ingrediente_id");

                    b.HasOne("Borgonha.Domain.Entities.Produto", null)
                        .WithMany("Receita")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_receita_itens_produtos_produto_id");
                });

            modelBuilder.Entity("Borgonha.Domain.Entities.Ingrediente", b =>
                {
                    b.Navigation("Movimentacoes");
                });

            modelBuilder.Entity("Borgonha.Domain.Entities.Produto", b =>
                {
                    b.Navigation("Receita");
                });

            modelBuilder.Entity("Borgonha.Domain.Entities.Venda", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
